"""initial_schema

Revision ID: 20a1eaa12e24
Revises: 
Create Date: 2026-04-09 04:10:08.340758

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20a1eaa12e24'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('default_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', 'archived', name='topicstatus'), nullable=False),
    sa.Column('transfer_deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scoped_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('creator', 'admin', 'moderator', 'recipient', name='memberrole'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('email_purged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creator_transfer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_member_id', sa.Uuid(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'denied', 'expired', name='transferstatus'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_circle_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('circle_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['circle_id'], ['circle.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_token_hash'), ['token_hash'], unique=True)

    op.create_table('update',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('author_member_id', sa.Uuid(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('update_id', sa.Uuid(), nullable=False),
    sa.Column('author_member_id', sa.Uuid(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wants_to_share', sa.Boolean(), nullable=False),
    sa.Column('relay_status', sa.Enum('pending', 'relayed', 'dismissed', name='relaystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['update_id'], ['update.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update_circle',
    sa.Column('update_id', sa.Uuid(), nullable=False),
    sa.Column('circle_id', sa.Uuid(), nullable=False),
    sa.Column('stamped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circle.id'], ),
    sa.ForeignKeyConstraint(['update_id'], ['update.id'], ),
    sa.PrimaryKeyConstraint('update_id', 'circle_id')
    )
    op.create_table('mod_response',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reply_id', sa.Uuid(), nullable=False),
    sa.Column('author_member_id', sa.Uuid(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sa.Enum('sender_only', 'sender_circle', 'all_circles', name='modresponsescope'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['reply_id'], ['reply.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relay',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reply_id', sa.Uuid(), nullable=False),
    sa.Column('relayed_by_member_id', sa.Uuid(), nullable=False),
    sa.Column('circle_id', sa.Uuid(), nullable=True),
    sa.Column('relayed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circle.id'], ),
    sa.ForeignKeyConstraint(['relayed_by_member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['reply_id'], ['reply.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relay')
    op.drop_table('mod_response')
    op.drop_table('update_circle')
    op.drop_table('reply')
    op.drop_table('update')
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_token_hash'))

    op.drop_table('token')
    op.drop_table('member_circle_history')
    op.drop_table('creator_transfer')
    op.drop_table('member')
    op.drop_table('circle')
    op.drop_table('topic')
    # ### end Alembic commands ###
