"""v0.2.0 notification system and attachments

Revision ID: e5ac2fcea29b
Revises: b2c3d4e5f6a7
Create Date: 2026-04-10 01:40:08.574290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e5ac2fcea29b'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', name='notificationchannel'), nullable=False),
    sa.Column('trigger', sa.Enum('new_update', 'new_reply', 'mod_response', 'invite', 'relay', 'digest', name='notificationtrigger'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'skipped', name='notificationstatus'), nullable=False),
    sa.Column('provider_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_log_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_log_topic_id'), ['topic_id'], unique=False)

    op.create_table('notification_preference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', name='notificationchannel'), nullable=False),
    sa.Column('trigger', sa.Enum('new_update', 'new_reply', 'mod_response', 'invite', 'relay', 'digest', name='notificationtrigger'), nullable=False),
    sa.Column('delivery_mode', sa.Enum('immediate', 'digest', 'muted', name='deliverymode'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preference_member_id'), ['member_id'], unique=False)

    op.create_table('attachment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('update_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['update_id'], ['update.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_update_id'), ['update_id'], unique=False)

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('phone_purged_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notification_channel', sa.Enum('email', 'sms', name='notificationchannel'), nullable=False))

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('photo_link_only', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_topic_short_code'), ['short_code'], unique=False)

    with op.batch_alter_table('update_circle', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_circle', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_short_code'))
        batch_op.drop_column('photo_link_only')
        batch_op.drop_column('short_code')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('notification_channel')
        batch_op.drop_column('phone_purged_at')
        batch_op.drop_column('phone')

    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_update_id'))
        batch_op.drop_index(batch_op.f('ix_attachment_topic_id'))

    op.drop_table('attachment')
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preference_member_id'))

    op.drop_table('notification_preference')
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_log_topic_id'))
        batch_op.drop_index(batch_op.f('ix_notification_log_member_id'))

    op.drop_table('notification_log')
    # ### end Alembic commands ###
